trigger: none

stages:
- stage: DEV
  jobs:
  - job: CleanRepo
    pool: Azure Pipelines
    steps:
    - checkout: self
      persistCredentials: true
      clean: true

  - job: Export
    pool: Azure Pipelines
    steps:
    - powershell: |
        Install-Module -Name Microsoft.PowerPlatform.Cds.Client -AllowClobber -Force
      displayName: 'Install PowerPlatform Tools'

    - powershell: |
        # Ton script pour exporter une solution de Power Platform
      displayName: 'Exporter la solution Power Platform'
