trigger: none

stages:
- stage: DEV
  jobs:
  - job: CleanRepo
    pool: Azure Pipelines
    steps:
    - checkout: self
      persistCredentials: true
      clean: true

  - job: Export
    pool: Azure Pipelines
    steps:
    - task: PowerPlatformToolInstaller@2
      inputs:
        DefaultVersion: true

    - task: PowerPlatformWhoAmI@1
      inputs:
        authenticationType: 'PowerPlatformSPN'
        PowerPlatformSPN: 'SPTel-PoCPatenteKDV_DEV-DV'
        Environment: '$(PowerPlatform.EnvironmentURL_DEV-DV)'

    - task: PowerPlatformExportSolution@2
      inputs:
        authenticationType: 'PowerPlatformSPN'
        PowerPlatformSPN: 'SPTel-PoCPatenteKDV_DEV-DV'
        Environment: '$(PowerPlatform.EnvironmentURL_DEV-DV)'
        SolutionName: '$(SolutionName)'
        SolutionOutputFile: '$(Build.ArtifactStagingDirectory)/$(SolutionName).zip'
        AsyncOperation: true
        MaxAsyncWaitTime: '60'